# fly.toml file generated for users-angular-challenge on 2023-03-30T18:05:18-04:00

app = "users-angular-challenge"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "mia"
processes = []

[[services]]
  internal_port = 4200
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
